#!/bin/sh
# prepare conf file
cp lcd4linux_base.conf lcd4linux.conf
echo "Layout Default {" >> lcd4linux.conf

stringContain() { [ -z "${2##*$1*}" ]; }

echo "Content-type: text/html"
echo ""


echo "Row1 { " >> lcd4linux.conf
if stringContain 'CPU' ${QUERY_STRING}; then 
	echo "Col1 'CPU'" >> lcd4linux.conf;
else 
	echo no; 
fi
if stringContain 'RAM' ${QUERY_STRING}; then 
        echo "Col20 'RAM'" >> lcd4linux.conf;
else 
        echo no; 
fi
echo "}" >> lcd4linux.conf


echo "Row2 { " >> lcd4linux.conf
if stringContain 'Pidgin' ${QUERY_STRING}; then 
        echo "Col1 'Pidgin'" >> lcd4linux.conf;
else 
        echo no; 
fi
if stringContain 'OS' ${QUERY_STRING}; then 
        echo "Col20 'OS'" >> lcd4linux.conf;
else 
        echo no; 
fi
echo "}" >> lcd4linux.conf

echo "Row3 { " >> lcd4linux.conf
if stringContain 'CPUinfo' ${QUERY_STRING}; then 
        echo "Col1 'CPUinfo'" >> lcd4linux.conf;
else 
        echo no; 
fi
if stringContain 'Busy' ${QUERY_STRING}; then 
        echo "Col20 'Busy'" >> lcd4linux.conf;
else 
        echo no; 
fi
echo "}" >> lcd4linux.conf


echo "Row4 { " >> lcd4linux.conf
if stringContain 'Load' ${QUERY_STRING}; then 
        echo "Col1 'Load'" >> lcd4linux.conf;
else 
        echo no; 
fi
if stringContain 'BusyBar' ${QUERY_STRING}; then 
        echo "Col20 'BusyBar'" >> lcd4linux.conf;
else 
        echo no; 
fi
echo "}" >> lcd4linux.conf



# fin de ifchier de conf
echo "
    }
Display 'Curses'
Layout  'Default'
" >> lcd4linux.conf
cp lcd4linux.conf /etc/lcd4linux.conf
echo "Configuration mise à jour"
