#! /bin/sh

### BEGIN INIT INFO
# Provides:          httpd
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: daemon for driving LCD based displays
# Description:       LCD4Linux is a small program that grabs information from
#                    the kernel and some subsystems and displays it on an
#                    external liquid crystal display.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/httpd
NAME=httpd
DESC=httpd

. /lib/lsb/init-functions
cp /etc/lcd4linux.conf /tmp/lcd4linux.conf
test -x $DAEMON || exit 0
DAEMON_OPTS="$ARGS"

set -e

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	/usr/sbin/httpd -vv -h /www > /tmp/httpd.log 2>&1 &
	log_daemon_msg "Starting $DESC" "$NAME"
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME" 
	pgrep -f httpd | xargs kill
	log_end_msg $?
	;;
  restart|force-reload)
	$0 stop
	sleep 2
	$0 start
	;;
  status)
	status_of_proc $DAEMON "$NAME"
	status=$?
	exit $status
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status|force-reload}" >&2
	exit 1
	;;
esac

exit 0

