#! /bin/sh

### BEGIN INIT INFO
# Provides:          lcdalexis
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: daemon for driving LCD based displays
# Description:       LCD4Linux is a small program that grabs information from
#                    the kernel and some subsystems and displays it on an
#                    external liquid crystal display.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/lcd4linux
NAME=lcdalexis
DESC=lcdalexis

. /lib/lsb/init-functions

test -x $DAEMON || exit 0
#test -f /etc/lcd4linux.conf || exit 0

#test -f /etc/default/lcd4linux && . /etc/default/lcd4linux
DAEMON_OPTS="$ARGS"

/usr/sbin/httpd -vv -h /www > /tmp/httpd.log
set -e

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	cp /etc/lcd4linux.conf /tmp/lcd4linux.conf
	lcd4linux -Fvv -f /tmp/lcd4linux.conf > /dev/tty2 2>&1 & echo $! > /tmp/pid
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME" 
	kill -9 $(cat /tmp/pid)
	log_end_msg $?
	;;
  restart|force-reload)
	$0 stop
	sleep 2
	$0 start
	;;
  status)
	status_of_proc $DAEMON "$NAME"
	status=$?
	exit $status
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status|force-reload}" >&2
	exit 1
	;;
esac

exit 0

