#!/bin/sh
# prepare conf file
BASE=/www/cgi-bin/lcd4linux_base.conf
FILE=/tmp/lcd4linux.conf
echo "${QUERY_STRING}" > /tmp/query
cp $BASE $FILE
echo "Layout Default {" >> $FILE
I=0
stringContain() { [ -z "${2##*$1*}" ]; }

echo "Content-type: text/html"
echo ""


if stringContain 'CPU' ${QUERY_STRING}; then 
	echo "Row$I { Col1 'CPU' }" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'RAM' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'RAM'}" >> $FILE;
	I=$(( $I + 1))
fi


if stringContain 'Pidgin' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'Pidgin'}" >> $FILE;
 	I=$(( $I + 1))
fi
if stringContain 'OS' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'OS'}" >> $FILE;
 	I=$(( $I + 1))
fi
if stringContain 'CPUinfo' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'CPUinfo'}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Busy' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'Busy'}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Load' ${QUERY_STRING}; then 
        echo "Row$I { Col1 'Load'}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'BusyBar' ${QUERY_STRING}; then 
        echo "Row$I {Col1 'BusyBar'}" >> $FILE;
	I=$(( $I + 1))
fi
echo "$i"
# fin de ifchier de conf
echo "
    }
Display 'Curses'
Layout  'Default'" >> $FILE
#cp lcd4linux.conf /etc/lcd4linux.conf
#kill -9 $(cat /tmp/pid)
service lcdalexis restart
echo "Configuration mise à jour"
