#!/bin/sh
# prepare conf file
BASE=/www/cgi-bin/lcd4linux_base.conf
FILE=/tmp/lcd4linux.conf
echo "${QUERY_STRING}" > /tmp/query
#service lcdalexis stop
rm -f $FILE
cp $BASE $FILE
echo "Layout Default {" >> $FILE
I=0
stringContain() { [ -z "${2##*$1*}" ]; }

echo "Content-type: text/html"
echo ""


if stringContain 'CPU' ${QUERY_STRING}; then 
	echo "Row$I { 
			Col1 'CPU' 
			Col20 'CPUinfo'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'RAM' ${QUERY_STRING}; then 
        echo "Row$I { 
		Col1 'RAM'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'OS' ${QUERY_STRING}; then 
        echo "Row$I { 
		Col1 'OS'
		}" >> $FILE;
 	I=$(( $I + 1))
fi
if stringContain 'CPUinfo' ${QUERY_STRING}; then 
        echo "Row$I { 
		Col1 'CPUinfo'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Busy' ${QUERY_STRING}; then 
        echo "Row$I { 
		Col1 'Busy'
		Col20 'BusyBar'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Load' ${QUERY_STRING}; then 
        echo "Row$I { 
		Col1 'Load'
		Col20 'LoadBar'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Disk' ${QUERY_STRING}; then 
        echo "Row$I {
		Col1 'Disk'
		Col20 'DiskBar'
		}" >> $FILE;
	I=$(( $I + 1))
fi
if stringContain 'Eth0' ${QUERY_STRING}; then 
        echo "Row$I {
                Col1 'Eth0'
                Col1 'Eth0Bar'
                }" >> $FILE;
        I=$(( $I + 1))
fi
if stringContain 'Temp' ${QUERY_STRING}; then 
        echo "Row$I {
                Col1 'Temp'
                Col1 'TempBar'
                }" >> $FILE;
        I=$(( $I + 1))
fi
if stringContain 'Uptime' ${QUERY_STRING}; then 
        echo "Row$I {
                Col1 'Uptime'
                }" >> $FILE;
        I=$(( $I + 1))
fi

echo "$I"
# fin de ifchier de conf
echo "
    }
Display 'Curses'
Layout  'Default' " >> $FILE
chmod 600 $FILE
chown root.root $FILE
#cp lcd4linux.conf /etc/lcd4linux.conf
#kill -9 $(cat /tmp/pid)
systemctl restart lcddanizan.service
#service lcdalexis start
echo "Configuration mise à jour"
